export const RC_GET_WORKPLACES = 'RC_GET_WORKPLACES';
export const RC_GET_WORKPLACES_SUCCESS = 'RC_GET_WORKPLACES_SUCCESS';
export const RC_GET_WORKPLACES_ERROR = 'RC_GET_WORKPLACES_ERROR';

export const RC_WORKPLACE_REMOVE = 'RC_WORKPLACE_REMOVE';
export const RC_WORKPLACE_REMOVE_SUCCESS = 'RC_WORKPLACE_REMOVE_SUCCESS';
export const RC_WORKPLACE_REMOVE_ERROR = 'RC_WORKPLACE_REMOVE_ERROR';

export const RC_WORKPLACE_GET = 'RC_WORKPLACE_GET';
export const RC_WORKPLACE_GET_SUCCESS = 'RC_WORKPLACE_GET_SUCCESS';
export const RC_WORKPLACE_GET_ERROR = 'RC_WORKPLACE_GET_ERROR';

export const RC_WORKPLACE_SAVE = 'RC_WORKPLACE_SAVE';
export const RC_WORKPLACE_SAVE_SUCCESS = 'RC_WORKPLACE_SAVE_SUCCESS';
export const RC_WORKPLACE_SAVE_ERROR = 'RC_WORKPLACE_SAVE_ERROR';
