export const GET_APPLICATIONS = 'GET_APPLICATIONS';
export const GET_APPLICATIONS_SUCCESS = 'GET_APPLICATIONS_SUCCESS';
export const GET_APPLICATIONS_ERROR = 'GET_APPLICATIONS_ERROR';

export const SELECT_APPLICATION = 'SELECT_APPLICATION';

export const CONNECT_APPLICATION = 'CONNECT_APPLICATION';
export const CONNECT_APPLICATION_SUCCESS = 'CONNECT_APPLICATION_SUCCESS';
export const CONNECT_APPLICATION_ERROR = 'CONNECT_APPLICATION_ERROR';

export const REMOVE_APPLICATION = 'REMOVE_APPLICATION';
export const REMOVE_APPLICATION_SUCCESS = 'REMOVE_APPLICATION_SUCCESS';
export const REMOVE_APPLICATION_ERROR = 'REMOVE_APPLICATION_ERROR';

export const SET_SHORTLIST = 'SET_SHORTLIST';
export const SET_SHORTLIST_SUCCESS = 'SET_SHORTLIST_SUCCESS';
export const SET_SHORTLIST_ERROR = 'SET_SHORTLIST_ERROR';

export const GET_MSG_APPLICATIONS = 'GET_MSG_APPLICATIONS';

export const SEND_MESSAGE = 'SEND_MESSAGE';
export const SEND_MESSAGE_SUCCESS = 'SEND_MESSAGE_SUCCESS';
export const SEND_MESSAGE_ERROR = 'SEND_MESSAGE_ERROR';
