platform :ios, '10.0'
use_frameworks!

target 'MyJobPitch' do

    pod 'AWSS3','2.4.11'
    pod 'RestKit'
    pod 'GoogleMaps'
    pod 'GooglePlaces'
    pod 'MBProgressHUD'
    pod 'UITextView+Placeholder'
    pod 'STPopup'
    pod 'MGSwipeTableCell'
    pod 'SVPullToRefresh'
    pod 'LLSimpleCamera'
    pod 'JSQMessagesViewController'
    pod 'JTSImageViewController'
    pod 'Nuke'
        
end
