# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-18 10:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mjp', '0018_postcode_lookup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobseeker',
            name='first_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='jobseeker',
            name='last_name',
            field=models.CharField(max_length=100),
        ),
    ]
