# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-14 21:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mjp', '0019_first_last_name_required'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobseeker',
            name='rating',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3),
        ),
    ]
