# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-16 13:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mjp', '0023_auto_20160518_1618'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobseeker',
            name='truth_confirmation',
            field=models.BooleanField(default=False),
        ),
    ]
