# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-20 19:59
from __future__ import unicode_literals

from django.db import migrations


def create_templates(apps, schema_editor):
    EmailTemplate = apps.get_model('mjp', 'EmailTemplate')
    EmailTemplate.objects.create(
        name='MESSAGE',
        from_address='no-reply@myjobpitch.com',
        subject=u"My Job Pitch notification from {{ from_name }}",
        body=u"You have a new message from {{ from_name }}\n"
             u"----------------------------------------------------------\n"
             u"\n"
             u"{{ message.content }}\n",
        context_help=u"{{ from_name }}\n"
                     u"{{ message.content }}\n"
                     u"{{ message.from_role }}\n"
                     u"{{ message.application }}\n"
                     u"{{ message.application.job_seeker }}\n"
                     u"{{ message.application.job }}\n"
                     u"{{ message.application.job.location }}\n"
                     u"{{ message.application.job.location.company }}",
    )

def delete_template(apps, schema_editor):
    EmailTemplate = apps.get_model('mjp', 'EmailTemplate')
    EmailTemplate.objects.filter(name='MESSAGE').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('mjp', '0025_emailtemplate'),
    ]

    operations = [
        migrations.RunPython(create_templates, reverse_code=delete_template)
    ]
