# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-20 21:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mjp', '0026_add_email_templates'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobseeker',
            name='email',
        ),
    ]
