# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-21 18:53
from __future__ import unicode_literals

from django.db import migrations


def create_token_stores(apps, schema_editor):
    TokenStore = apps.get_model('mjp', 'TokenStore')
    Business = apps.get_model('mjp', 'Business')
    for business in Business.objects.all():
        business.token_store = TokenStore.objects.create(
            tokens=100,
            user=business.users.first(),
        )
        business.save()


def delete_token_stores(apps, schema_editor):
    TokenStore = apps.get_model('mjp', 'TokenStore')
    TokenStore.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('mjp', '0028_add_tokens'),
    ]

    operations = [
        migrations.RunPython(create_token_stores, reverse_code=delete_token_stores)
    ]
