# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-21 18:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mjp', '0029_create_token_stores'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='token_store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='businesses', to='mjp.TokenStore'),
        ),
    ]
