# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-09-15 13:47
from __future__ import unicode_literals

from django.db import migrations


def create_initial_tokens(apps, schema_editor):
    InitialTokens = apps.get_model('mjp', 'InitialTokens')
    InitialTokens.objects.create(tokens=100)


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('mjp', '0031_initialtokens'),
    ]

    operations = [
        migrations.RunPython(create_initial_tokens, reverse_code=noop),
    ]

