# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-09-15 14:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mjp', '0032_create_initial_tokens'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='can_create_businesses',
            field=models.BooleanField(default=False),
        ),
    ]
