# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-05-02 22:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mjp', '0034_androidpurchase'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductTokens',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=255)),
                ('tokens', models.IntegerField()),
            ],
        ),
    ]
