# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-05-02 23:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mjp', '0035_producttokens'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='producttokens',
            options={'verbose_name_plural': 'product tokens'},
        ),
    ]
