# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-07-07 09:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mjp', '0036_auto_20170502_2345'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sector',
            options={'ordering': ('priority',)},
        ),
        migrations.AddField(
            model_name='sector',
            name='priority',
            field=models.IntegerField(default=10, help_text=b'Lower first'),
        ),
    ]
