# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-08-22 15:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mjp', '0037_sector_priority'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayPalProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_code', models.CharField(max_length=255, unique=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tokens', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'paypal products',
            },
        ),
        migrations.AlterModelOptions(
            name='sector',
            options={'ordering': ('priority', 'name')},
        ),
    ]
