# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-10-02 19:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mjp', '0038_paypal_product'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paypalproduct',
            options={'ordering': ('tokens',), 'verbose_name_plural': 'paypal products'},
        ),
    ]
