# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-10-11 08:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mjp', '0039_auto_20171002_1906'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='location',
            options={'ordering': ('name',), 'verbose_name': 'Work Place', 'verbose_name_plural': 'Work Places'},
        ),
    ]
