# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-11-02 18:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mjp', '0041_jobseeker_national_insurance_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paypalproduct',
            options={'ordering': ('tokens',), 'verbose_name': 'paypal product', 'verbose_name_plural': 'paypal products'},
        ),
        migrations.AlterModelOptions(
            name='producttokens',
            options={'verbose_name': 'Google play product', 'verbose_name_plural': 'Google play products'},
        ),
    ]
