# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-11-23 01:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mjp', '0042_auto_20171102_1853'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmailTemplate',
        ),
    ]
