# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-12-05 23:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mjp', '0043_delete_emailtemplate'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppDeprecation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[(b'ANDROID', b'Android'), (b'IOS', b'iOS')], max_length=255, unique=True)),
                ('warning', models.CharField(max_length=255)),
                ('error', models.CharField(max_length=255)),
            ],
        ),
    ]
