# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2018-02-12 20:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mjp', '0044_appdeprecation'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobseeker',
            name='pitch_reminder_sent',
            field=models.DateTimeField(null=True),
        ),
    ]
