# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2018-03-02 14:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mjp', '0045_jobseeker_pitch_reminder_sent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='email_public',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='location',
            name='mobile_public',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='location',
            name='telephone_public',
            field=models.BooleanField(default=False),
        ),
    ]
