# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2018-03-02 14:56
from __future__ import unicode_literals

from django.db import migrations


def copy_old_to_new(apps, schema_editor):
    Business = apps.get_model('mjp', 'Business')
    BusinessUser = apps.get_model('mjp', 'BusinessUser')
    for business in Business.objects.all():
        for user in business.users.all():
            BusinessUser.objects.create(business=business, user=user)


def copy_new_to_old(apps, schema_editor):
    Business = apps.get_model('mjp', 'Business')
    for business in Business.objects.all():
        business.users = business.new_users.all()


class Migration(migrations.Migration):

    dependencies = [
        ('mjp', '0047_add_temp_business_users_field'),
    ]

    operations = [
        migrations.RunPython(copy_old_to_new, reverse_code=copy_new_to_old),
    ]
