# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2018-03-02 16:37
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mjp', '0049_remove_business_users'),
    ]

    operations = [
        migrations.RenameField(
            model_name='business',
            old_name='new_users',
            new_name='users',
        ),
        migrations.AlterField(
            model_name='business',
            name='users',
            field=models.ManyToManyField(related_name='businesses', through='mjp.BusinessUser',
                                         to=settings.AUTH_USER_MODEL),
        ),
    ]
