# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2018-03-26 20:59
from __future__ import unicode_literals

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mjp', '0050_rename_temp_business_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.TextField(default=uuid.uuid4, editable=False)),
                ('video', models.URLField(max_length=512, null=True)),
                ('thumbnail', models.URLField(max_length=512, null=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='mjp.Job')),
            ],
        ),
    ]
