# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2018-03-26 22:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mjp', '0050_rename_temp_business_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobseeker',
            name='age_public',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='jobseeker',
            name='email_public',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='jobseeker',
            name='mobile_public',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='jobseeker',
            name='nationality_public',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='jobseeker',
            name='sex_public',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='jobseeker',
            name='telephone_public',
            field=models.BooleanField(default=False),
        ),
    ]
