# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2018-06-03 21:35
from __future__ import unicode_literals

from django.db import migrations


def create_objects(apps, schema_editor):
    ApplicationStatus = apps.get_model('mjp', 'ApplicationStatus')
    for name in ['ACCEPTED', 'DECLINED']:
        obj = ApplicationStatus()
        obj.name = name
        obj.save()


def delete_objects(apps, schema_editor):
    ApplicationStatus = apps.get_model('mjp', 'ApplicationStatus')
    ApplicationStatus.objects.filter(name__in=['ACCEPTED', 'DECLINED']).delete()


class Migration(migrations.Migration):
    dependencies = [('mjp', '0054_interviews')]
    operations = [migrations.RunPython(create_objects, reverse_code=delete_objects)]
