# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2018-06-03 23:59
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mjp', '0055_new_application_statuses'),
    ]

    operations = [
        migrations.AddField(
            model_name='interview',
            name='cancelled',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='interview',
            name='cancelled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mjp.Role'),
        ),
    ]
