# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2018-07-12 13:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mjp', '0056_interview_cancelled'),
    ]

    operations = [
        migrations.AddField(
            model_name='interview',
            name='status',
            field=models.CharField(choices=[
                (b'PENDING', b'Pending'),
                (b'ACCEPTED', b'Accepted'),
                (b'COMPLETED', b'Complete'),
                (b'CANCELLED', b'Cancelled'),
            ], default=b'PENDING', max_length=32),
        ),
    ]
