# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2018-08-07 07:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mjp', '0058_profile_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='requires_cv',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='job',
            name='requires_pitch',
            field=models.BooleanField(default=True),
        ),
    ]
