# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2018-10-02 21:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0003_auto_20181002_2159'),
        ('mjp', '0063_job_hr_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='employees',
            field=models.ManyToManyField(related_name='employees', through='hr.EmployeeUser', to='hr.Employee'),
        ),
    ]
