# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2018-10-02 22:36
from __future__ import unicode_literals

from django.db import migrations


def create_objects(apps, schema_editor):
    ApplicationStatus = apps.get_model('mjp', 'ApplicationStatus')
    obj = ApplicationStatus()
    obj.name = 'OFFERED'
    obj.save()


def delete_objects(apps, schema_editor):
    ApplicationStatus = apps.get_model('mjp', 'ApplicationStatus')
    ApplicationStatus.objects.filter(name='OFFERED').delete()


class Migration(migrations.Migration):
    dependencies = [('mjp', '0064_user_employees')]
    operations = [migrations.RunPython(create_objects, reverse_code=delete_objects)]
