# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2018-10-04 13:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mjp', '0065_new_application_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='address',
        ),
        migrations.RemoveField(
            model_name='location',
            name='postcode_lookup',
        ),
    ]
