# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2018-10-04 15:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mjp', '0066_auto_20181004_1337'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='city',
            field=models.CharField(blank=True, max_length=1024),
        ),
        migrations.AddField(
            model_name='location',
            name='country',
            field=models.CharField(blank=True, max_length=1024),
        ),
        migrations.AddField(
            model_name='location',
            name='postcode',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='location',
            name='region',
            field=models.CharField(blank=True, max_length=1024),
        ),
        migrations.AddField(
            model_name='location',
            name='street',
            field=models.CharField(blank=True, max_length=1024),
        ),
        migrations.AddField(
            model_name='location',
            name='street_number',
            field=models.CharField(blank=True, max_length=1024),
        ),
    ]
