# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2018-10-14 13:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mjp', '0067_auto_20181004_1503'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='employees',
        ),
    ]
