# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2018-10-14 14:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mjp', '0068_remove_user_employees'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='employee_level',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='business',
            name='hr_access',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='business',
            name='suspended',
            field=models.BooleanField(default=False),
        ),
    ]
