export const JS_PROFILE_LOAD = 'JS_PROFILE_LOAD';
export const JS_PROFILE_LOAD_SUCESS = 'JS_PROFILE_LOAD_SUCESS';
export const JS_PROFILE_LOAD_ERROR = 'JS_PROFILE_LOAD_ERROR';

export const JS_PROFILE_SAVE = 'JS_PROFILE_SAVE';
export const JS_PITCH_UPLOAD = 'JS_PITCH_UPLOAD';
export const JS_PROFILE_SAVE_SUCCESS = 'JS_PROFILE_SAVE_SUCCESS';
export const JS_PROFILE_SAVE_ERROR = 'JS_PROFILE_SAVE_ERROR';
