export const JS_GET_APPLICATIONS = 'JS_GET_APPLICATIONS';
export const JS_GET_APPLICATIONS_SUCCESS = 'JS_GET_APPLICATIONS_SUCCESS';
export const JS_GET_APPLICATIONS_ERROR = 'JS_GET_APPLICATIONS_ERROR';
