export const RC_GET_BUSINESSES = 'RC_GET_BUSINESSES';
export const RC_GET_BUSINESSES_SUCCESS = 'RC_GET_BUSINESSES_SUCCESS';
export const RC_GET_BUSINESSES_ERROR = 'RC_GET_BUSINESSES_ERROR';

export const RC_BUSINESS_REMOVE = 'RC_BUSINESS_REMOVE';
export const RC_BUSINESS_REMOVE_SUCCESS = 'RC_BUSINESS_REMOVE_SUCCESS';
export const RC_BUSINESS_REMOVE_ERROR = 'RC_BUSINESS_REMOVE_ERROR';

export const RC_BUSINESS_GET = 'RC_BUSINESS_GET';
export const RC_BUSINESS_GET_SUCCESS = 'RC_BUSINESS_GET_SUCCESS';
export const RC_BUSINESS_GET_ERROR = 'RC_BUSINESS_GET_ERROR';

export const RC_BUSINESS_SAVE = 'RC_BUSINESS_SAVE';
export const RC_BUSINESS_SAVE_SUCCESS = 'RC_BUSINESS_SAVE_SUCCESS';
export const RC_BUSINESS_SAVE_ERROR = 'RC_BUSINESS_SAVE_ERROR';
