export const JS_JOBPROFILE_LOAD = 'JS_JOBPROFILE_LOAD';
export const JS_JOBPROFILE_LOAD_SUCESS = 'JS_JOBPROFILE_LOAD_SUCESS';
export const JS_JOBPROFILE_LOAD_ERROR = 'JS_JOBPROFILE_LOAD_ERROR';

export const JS_JOBPROFILE_SAVE = 'JS_JOBPROFILE_SAVE';
export const JS_JOBPROFILE_SAVE_SUCCESS = 'JS_JOBPROFILE_SAVE_SUCCESS';
export const JS_JOBPROFILE_SAVE_ERROR = 'JS_JOBPROFILE_SAVE_ERROR';
