export const RC_GET_JOBS = 'RC_GET_JOBS';
export const RC_GET_JOBS_WITH_SELECTEDJOB = 'RC_GET_JOBS_WITH_SELECTEDJOB';
export const RC_GET_JOBS_SUCCESS = 'RC_GET_JOBS_SUCCESS';
export const RC_GET_JOBS_ERROR = 'RC_GET_JOBS_ERROR';

export const RC_JOB_REMOVE = 'RC_JOB_REMOVE';
export const RC_JOB_REMOVE_SUCCESS = 'RC_JOB_REMOVE_SUCCESS';
export const RC_JOB_REMOVE_ERROR = 'RC_JOB_REMOVE_ERROR';

export const RC_JOB_UPDATE = 'RC_JOB_UPDATE';
export const RC_JOB_UPDATE_SUCCESS = 'RC_JOB_UPDATE_SUCCESS';
export const RC_JOB_UPDATE_ERROR = 'RC_JOB_UPDATE_ERROR';

export const RC_JOB_GET = 'RC_JOB_GET';
export const RC_JOB_GET_SUCCESS = 'RC_JOB_GET_SUCCESS';
export const RC_JOB_GET_ERROR = 'RC_JOB_GET_ERROR';

export const RC_JOB_SAVE = 'RC_JOB_SAVE';
export const RC_JOB_SAVE_SUCCESS = 'RC_JOB_SAVE_SUCCESS';
export const RC_JOB_SAVE_ERROR = 'RC_JOB_SAVE_ERROR';

export const RC_JOB_SELECT = 'RC_JOB_SELECT';
