export const RC_GET_JOBSEEKERS = 'RC_GET_JOBSEEKERS';
export const RC_GET_JOBSEEKERS_SUCCESS = 'RC_GET_JOBSEEKERS_SUCCESS';
export const RC_GET_JOBSEEKERS_ERROR = 'RC_GET_JOBSEEKERS_ERROR';

export const RC_SELECT_JOBSEEKER = 'RC_SELECT_JOBSEEKER';

export const RC_CONNECT_JOBSEEKER = 'RC_CONNECT_JOBSEEKER';
export const RC_CONNECT_JOBSEEKER_SUCCESS = 'RC_CONNECT_JOBSEEKER_SUCCESS';
export const RC_CONNECT_JOBSEEKER_ERROR = 'RC_CONNECT_JOBSEEKER_ERROR';

export const RC_REMOVE_JOBSEEKER = 'RC_REMOVE_JOBSEEKER';
