// general

export const REGISTER = 'REGISTER';
export const LOGIN = 'LOGIN';
export const LOGOUT = 'LOGOUT';
export const RESET_PASSWORD = 'RESET_PASSWORD';
export const CHANGE_PASSWORD = 'CHANGE_PASSWORD';
export const GET_USERDATA = 'GET_USERDATA';
export const UPDATE_AUTH = 'UPDATE_AUTH';

export const GET_APPLICATIONS = 'GET_APPLICATIONS';
export const UPDATE_APPLICATION = 'UPDATE_APPLICATION';
export const REMOVE_APPLICATION = 'REMOVE_APPLICATION';
export const READ_MESSAGE = 'READ_MESSAGE';
export const SEND_MESSAGE = 'SEND_MESSAGE';

export const SAVE_INTERVIEW = 'SAVE_INTERVIEW';
export const CHANGE_INTERVIEW = 'CHANGE_INTERVIEW';
export const COMPLETE_INTERVIEW = 'COMPLETE_INTERVIEW';
export const REMOVE_INTERVIEW = 'REMOVE_INTERVIEW';

// recruiter

export const RC_FIND_JOBSEEKERS = 'RC_FIND_JOBSEEKERS';
export const RC_CONNECT_JOBSEEKER = 'RC_CONNECT_JOBSEEKER';
export const RC_REMOVE_JOBSEEKER = 'RC_REMOVE_JOBSEEKER';

export const RC_GET_BUSINESSES = 'RC_GET_BUSINESSES';
export const RC_UPDATE_BUSINESS = 'RC_UPDATE_BUSINESS';
export const RC_SAVE_BUSINESS = 'RC_SAVE_BUSINESS';
export const RC_REMOVE_BUSINESS = 'RC_REMOVE_BUSINESS';
export const RC_SELECT_BUSINESS = 'RC_SELECT_BUSINESS';
export const RC_PURCHASE = 'RC_PURCHASE';

export const RC_GET_WORKPLACES = 'RC_GET_WORKPLACES';
export const RC_UPDATE_WORKPLACE = 'RC_UPDATE_WORKPLACE';
export const RC_SAVE_WORKPLACE = 'RC_SAVE_WORKPLACE';
export const RC_REMOVE_WORKPLACE = 'RC_REMOVE_WORKPLACE';

export const RC_GET_JOBS = 'RC_GET_JOBS';
export const RC_UPDATE_JOB = 'RC_UPDATE_JOB';
export const RC_SAVE_JOB = 'RC_SAVE_JOB';
export const RC_REMOVE_JOB = 'RC_REMOVE_JOB';

export const RC_GET_USERS = 'RC_GET_USERS';
export const RC_SAVE_USER = 'RC_SAVE_USER';
export const RC_RESEND_INVITATION = 'RC_RESEND_INVITATION';
export const RC_REMOVE_USER = 'RC_REMOVE_USER';

// jobseeker

export const JS_FIND_JOBS = 'JS_FIND_JOBS';
export const JS_APPLY_JOB = 'JS_APPLY_JOB';
export const JS_REMOVE_JOB = 'JS_REMOVE_JOB';
export const JS_GET_PUBLIC_JOB = 'JS_GET_PUBLIC_JOB';
export const JS_GET_PUBLIC_WORKPLACE = 'JS_GET_PUBLIC_WORKPLACE';

export const JS_SAVE_PROFILE = 'JS_SAVE_PROFILE';
export const JS_SAVE_JOBPROFILE = 'JS_SAVE_JOBPROFILE';
export const JS_UPLOAD_PITCH = 'JS_UPLOAD_PITCH';
export const JS_UPLOAD_JOBPITCH = 'JS_UPLOAD_JOBPITCH';
