// general

export const REGISTER = 'REGISTER';
export const LOGIN = 'LOGIN';
export const LOGOUT = 'LOGOUT';
export const RESET_PASSWORD = 'RESET_PASSWORD';
export const CHANGE_PASSWORD = 'CHANGE_PASSWORD';
export const GET_USERDATA = 'GET_USERDATA';
export const UPDATE_AUTH = 'UPDATE_AUTH';

export const APPLICATIONS_UPDATE = 'APPLICATIONS_UPDATE';
export const GET_APPLICATIONS = 'GET_APPLICATIONS';
export const CONNECT_APPLICATION = 'CONNECT_APPLICATION';
export const UPDATE_APPLICATION = 'UPDATE_APPLICATION';
export const REMOVE_APPLICATION = 'REMOVE_APPLICATION';
export const READ_MESSAGE = 'READ_MESSAGE';
export const SEND_MESSAGE = 'SEND_MESSAGE';
export const UPDATE_MESSAGE_BY_INTERVIEW = 'UPDATE_MESSAGE_BY_INTERVIEW';

// recruiter

export const RC_FIND_JOBSEEKERS = 'RC_FIND_JOBSEEKERS';
export const RC_CONNECT_JOBSEEKER = 'RC_CONNECT_JOBSEEKER';
export const RC_REMOVE_JOBSEEKER = 'RC_REMOVE_JOBSEEKER';

export const RC_BUSINESSES_UPDATE = 'RC_BUSINESSES_UPDATE';
export const RC_GET_BUSINESSES = 'RC_GET_BUSINESSES';
export const RC_SAVE_BUSINESS = 'RC_SAVE_BUSINESS';
export const RC_REMOVE_BUSINESS = 'RC_REMOVE_BUSINESS';
export const RC_SELECT_BUSINESS = 'RC_SELECT_BUSINESS';
export const RC_PURCHASE = 'RC_PURCHASE';

export const RC_WORKPLACES_UPDATE = 'RC_WORKPLACES_UPDATE';
export const RC_GET_WORKPLACES = 'RC_GET_WORKPLACES';
export const RC_SAVE_WORKPLACE = 'RC_SAVE_WORKPLACE';
export const RC_REMOVE_WORKPLACE = 'RC_REMOVE_WORKPLACE';

export const RC_JOBS_UPDATE = 'RC_JOBS_UPDATE';
export const RC_GET_JOBS = 'RC_GET_JOBS';
export const RC_SAVE_JOB = 'RC_SAVE_JOB';
export const RC_REMOVE_JOB = 'RC_REMOVE_JOB';
export const RC_UPDATE_JOB = 'RC_UPDATE_JOB';

export const RC_USERS_UPDATE = 'RC_USERS_UPDATE';
export const RC_GET_USERS = 'RC_GET_USERS';
export const RC_SAVE_USER = 'RC_SAVE_USER';
export const RC_REMOVE_USER = 'RC_REMOVE_USER';
export const RC_UPDATE_USER = 'RC_UPDATE_USER';
export const RC_RESEND_INVITATION = 'RC_RESEND_INVITATION';

export const INTERVIEWS_UPDATE = 'INTERVIEWS_UPDATE';
export const GET_INTERVIEWS = 'GET_INTERVIEWS';
export const SAVE_INTERVIEW = 'SAVE_INTERVIEW';
export const REMOVE_INTERVIEW = 'REMOVE_INTERVIEW';
export const UPDATE_INTERVIEW = 'UPDATE_INTERVIEW';
export const CHANGE_INTERVIEW = 'CHANGE_INTERVIEW';

// jobseeker

export const JS_FIND_JOBS = 'JS_FIND_JOBS';
export const JS_FIND_PUBLIC_JOB = 'JS_FIND_PUBLIC_JOB';
export const JS_FIND_PUBLIC_JOB_LIST = 'JS_FIND_PUBLIC_JOB_LIST';
export const JS_APPLY_JOB = 'JS_APPLY_JOB';
export const JS_REMOVE_JOB = 'JS_REMOVE_JOB';

export const JS_APPS_UPDATE = 'JS_APPS_UPDATE';
export const JS_GET_APPS = 'JS_GET_APPS';

export const JS_SAVE_PROFILE = 'JS_SAVE_PROFILE';
export const JS_SAVE_JOBPROFILE = 'JS_SAVE_JOBPROFILE';
export const JS_UPLOAD_PITCH = 'JS_UPLOAD_PITCH';
export const JS_UPLOAD_JOBPITCH = 'JS_UPLOAD_JOBPITCH';
