platform :ios, '8.0'
use_frameworks!

target 'MyJobPitch' do
    
    pod 'RestKit'
    pod 'DownPicker'
    pod 'GoogleMaps'
    pod 'GooglePlaces'
    pod 'AWSS3'
    pod 'SVProgressHUD'
       
end
