from django.conf.urls import patterns, include, url
from django.contrib.auth import views as auth_views

urlpatterns = patterns('web.views',
    url(r'^$', 'index'),
	url(r'^login/$', 'login'),
	url(r'^registration/$', 'registration'),
    url(r'^password-change/$', auth_views.password_change, name='password_change'),
    url(r'^password-change/done/$', auth_views.password_change_done, name='password_change_done'),
    url(r'^password-reset/$', auth_views.password_reset, name='password_reset'),
    url(r'^password-reset/done/$', auth_views.password_reset_done, name='password_reset_done'),
    url(r'^password-reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
		auth_views.password_reset_confirm, name='password_reset_confirm'),
    url(r'^password-reset/complete/$', auth_views.password_reset_complete, name='password_reset_complete'),
	url(r'^profile/$', 'profile'),
	url(r'^profile/create-job-seeker/$', 'create_profile_job_seeker'),
	url(r'^profile/create-business/$', 'create_business'),
	url(r'^profile/create-location/$', 'create_location'),
	url(r'^profile/edit-job-seeker/$', 'edit_profile_job_seeker'),
	url(r'^profile/list-businesses/$', 'list_businesses'),
	url(r'^profile/list-locations/$', 'list_locations'),
	url(r'^profile/list-jobs/$', 'list_jobs'),
	url(r'^profile/create-job/$', 'create_job'),
	url(r'^profile/edit-job/$', 'edit_job'),
	url(r'^profile/pitch/$', 'pitch'),	
	url(r'^profile/job-preferences/$', 'job_preferences'),	
	url(r'^logout/$', 'logout'),
	url(r'^terms-conditions/$', 'terms_conditions'),
	url(r'^privacy-policy/$', 'privacy_policy'),
	url(r'^mobile-app/$', 'mobile_app'),
	url(r'^about/$', 'about'),
	url(r'^applications/$', 'applications'),
	url(r'^connections/$', 'connections'),
	url(r'^messages/$', 'messages'),
	url(r'^jobs/$', 'jobs'),
	url(r'^single-job/$', 'single_job'),
	url(r'^dashboard/$', 'dashboard'),
	url(r'^profile/edit-job-preferences/$', 'edit_job_preferences'),
	url(r'^find-staff/$', 'find_staff'),
	url(r'^profile/viewpitch/$', 'viewpitch'),
	url(r'^profile/edit-pitch/$', 'edit_pitch'),
	url(r'^profile/edit-location/$', 'edit_location'),
	url(r'^profile/edit-business/$', 'edit_business'),
)
