from django.conf.urls import patterns, include, url

urlpatterns = patterns('web.views',
    url(r'^$', 'index'),
	url(r'^login/$', 'login'),
	url(r'^registration/$', 'registration'),
	url(r'^profile/password-reset/$', 'password_reset'),
	url(r'^profile/password-reset-confirm/$', 'password_reset_confirm'),
	url(r'^profile/password-change/$', 'password_change'),
	url(r'^profile/$', 'profile'),
	url(r'^profile/create-job-seeker/$', 'create_profile_job_seeker'),
	url(r'^profile/create-business/$', 'create_profile_business'),
	url(r'^profile/edit-job-seeker/$', 'edit_profile_job_seeker'),
	url(r'^profile/edit-business/$', 'edit_profile_business'),
	url(r'^profile/list-businesses/$', 'list_businesses'),
	url(r'^profile/list-locations/$', 'list_locations'),
	url(r'^profile/pitch/$', 'pitch'),	
	url(r'^logout/$', 'logout'),
	url(r'^terms-conditions/$', 'terms_conditions'),
	url(r'^privacy-policy/$', 'privacy_policy'),
	url(r'^mobile-app/$', 'mobile_app'),
	url(r'^about/$', 'about'),
)
