# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2018-10-01 09:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='profile_image',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to=b'employee-profile/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='profile_thumb',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to=b'employee-profile/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='job',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
