# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2018-10-02 21:59
from __future__ import unicode_literals

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0002_auto_20181001_0940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeuser',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
