# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2018-10-14 13:17
from __future__ import unicode_literals

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mjp', '0068_remove_user_employees'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hr', '0003_auto_20181002_2159'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeeuser',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='employeeuser',
            name='user',
        ),
        migrations.AddField(
            model_name='employee',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='employee',
            name='job',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='hr.Job'),
        ),
        migrations.DeleteModel(
            name='EmployeeUser',
        ),
    ]
