# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2018-11-01 16:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mjp', '0069_hr_and_suspended_flags'),
        ('hr', '0005_employee_allow_blank'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='business',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='mjp.Business'),
            preserve_default=False,
        ),
    ]
